# Generated by Django 2.2.5 on 2020-01-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200131_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
